 
backend:
  name: github # FALTA CONFIGURAR GIT Y NERTLIFY PARA QUE SE COMUNIQUEN!!!!!!!!!
  repo: albirasolutions/UOC_WebRI
  branch: victor
  #base_url: http://uocwebrisupport.s3-website-eu-west-1.amazonaws.com
  #client_id: 05de47c07b638caed5f9
  #name: git-gateway

media_folder: "static/img" # Media files will be stored in the repo under static/img/
public_folder: "/img"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "principal"
    label: "Principal"
    folder: "content/principal"
    format: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    #slug: "principal.{{language}}"
    files:
      - file: "content/principal/principal.md"
        label: "Principal"
        name: "principal"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "content/principal/principal.{{language}}.md"
        label: "Menu"
        name: "menu"
        fields:
          - {label: title, name: title, widget: string}
          - label: ambits_especialitzacio
            name : ambits_especialitzacio
            widget: list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: ods
            name : ods 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
          - label: sector_productiu
            name : sector_productiu 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
          - label: centre
            name : centre 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
  - name: "cercador"
    label: "Cercador"
    folder: "content/cercador"
    format: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    #slug: "cercador.{{language}}"
    files:
      - file: "content/cercador/cercador.{{language}}.md"
        label: "cercador"
        name: "Cercador"
        fields:
          - {label: title, name: title, widget: string}
          - label: ambits_especialitzacio
            name : ambits_especialitzacio
            widget: list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: ods
            name : ods 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
          - label: centre
            name : centre 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
  - name: "mapa-ambits-recerca"
    label: "mapa-ambits-recerca"
    folder: "content/mapa-ambits-recerca"
    format: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    #slug: "mapa-ambits-recerca.{{language}}"
    files:
      - file: "content/cercador/mapa-ambits-recerca.{{language}}.md"
        label: "mapa-ambits-recerca"
        name: "mapa-ambits-recerca"
        fields:
          - {label: title, name: title, widget: string}
          - label: ambits_especialitzacio
            name : ambits_especialitzacio
            widget: list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: ambit
            name : ambit 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
  - name: "contacte"
    label: "contacte"
    folder: "content/contacte"
    format: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    #slug: "mapa-ambits-recerca.{{language}}"
    files:
      - file: "content/contacte/contacte.{{language}}.md"
        name: "contacte"
        label: "contacte"
        fields:
          - {label: title, name: title, widget: string}
          - label: section
            name: section
            widget: list 
            fields:
                - label: contact_obj
                  name: contact_obj
                  widget: object,
                  fields :
                    - {label: form, name: form, widget: boolean}
                    - {label: name, name : name, widget: string}
                    - {label: addr_1, name: addr_1, widget: Text}
                    - {label: addr_2, name: addr_2, widget: Text}
                    - label: phones
                      name: phones
                      widget: list 
                      field: {widget: number, valueType: int}
                    - label: urls
                      name: urls
                      widget: list
                      field: {widget: Text}
          - label: motius
            name: motius
            widget: list 
            fields:
              - {label: display_name, name : display_name, widget: string}
              - {label: value, name: value, widget: Text}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false