 
backend:
  name: github # FALTA CONFIGURAR GIT Y NERTLIFY PARA QUE SE COMUNIQUEN!!!!!!!!!
  repo: albirasolutions/UOC_WebRI
  branch: victor
  #base_url: https://netlify-oauth.azurewebsites.net
  #client_id: b135b68c2ba0bd0c422a
  #name: git-gateway

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "principal"
    label: "Principal"
    folder: "content"
    format: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    slug: "principal.{{language}}"
    files:
      - file: "content/principal/principal.md"
        label: "Principal"
        name: "principal"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "content/principal/{{slug}}.md"
        label: "Menu"
        name: "menu"
        fields:
          - {label: ambits_especialitzacio, name: ambits_especialitzacio, widget: list, fields: [
               - {label: display_name, name : display_name, widget: string}
               - {label: value, name: value, widget: string}]}
          - {label: ods, name: ods, widget: list, fields: [
                - {label: display_name, name : display_name, widget: string}
                - {label: value, name: value, widget: string}
                - {label: img, name: img, widget : image}]
            }
          - {label: centre , name: centre , widget: list, fields: [
                - {label: display_value, name: display_value, widget : string}
                - {label: value, name: value, widget: string}]
            }
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false