 
backend:
  name: github # FALTA CONFIGURAR GIT Y NERTLIFY PARA QUE SE COMUNIQUEN!!!!!!!!!
  repo: albirasolutions/UOC_WebRI
  branch: victor
  #base_url: https://netlify-oauth.azurewebsites.net
  #client_id: 05de47c07b638caed5f9
  #name: git-gateway

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "principal"
    label: "Principal"
    folder: "content/principal/"
    #format: "json-frontmatter"
    extension: "json"
    #filter: {field: "contenttype", value: "section"}    
    create: true
    slug: "principal.{{language}}"
    fields:
          - {label: title, name: title, widget: string}
          - label: ambits_especialitzacio
            name : ambits_especialitzacio
            widget: list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: ods
            name : ods, 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
          - label: centre
            name : centre 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false