 
backend:
  name: github # FALTA CONFIGURAR GIT Y NERTLIFY PARA QUE SE COMUNIQUEN!!!!!!!!!
  repo: albirasolutions/UOC_WebRI
  branch: victor
  #base_url: http://uoc-web-ri.s3-eu-west-1.amazonaws.com
  #client_id: 05de47c07b638caed5f9
  #name: git-gateway

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "principal"
    label: "Principal"
    files:
      - label: "Title"
        name: "title"
        file: "content/principal/principal.md"
        fields:
          - {label: title, name: title, widget: string}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false